### ISSUE TITLE
Questions about radgraph_entity_graphs.json

### ISSUE THREAD

**Issue by Roypic** [xiaoman-zhang/KAD#15]

**Comment by Liqq1** [comment]
Hello, sorry to bother you. May I ask how you obtained the 'radgraph_entity_graphs.json' file when reproducing the code? Did you use the file provided by the author and modify the path in them？

**Comment by Roypic** [comment]
You can find it on baiduyun 
![image](https://github.com/xiaoman-zhang/KAD/assets/50487307/851bb627-f8a1-46b2-9c49-81637037a781)

**Comment by Liqq1** [comment]
Thank you!
Yes, I can find them in Baidu Cloud. What I'd like to confirm is, when using them, did you directly modify the file paths？(since the current paths are related to the author? e.g. s3://zhangxiaoman_share/....) Or do we have another way to generate this JSON file directly without the need to modify it based on the files provided by the author?

**Comment by Roypic** [comment]
I just directly change the path with a simple script.

**Comment by Liqq1** [comment]
got it. thank u😊

**Comment by Liqq1** [comment]
Sorry, let me clarify. In my previous question, I meant to inquire about 'rad_graph_metric_train.json,' but I mistakenly wrote 'radgraph_entity_graphs.json.' Could you please help me confirm whether you directly modified the paths in 'rad_graph_metric_train.json' (e.g., 's3://zhangxiaoman_share/...')?
